export const createEarthquakeSlice = (set) => ({
  isPlacingEpicenter: false,
  setIsPlacingEpicenter: (val) => set({ isPlacingEpicenter: val }),

  earthquakeEpicenter: null,
  setEarthquakeEpicenter: (epicenter) => set({ earthquakeEpicenter: epicenter }),

  earthquakeMagnitude: 5.0,
  setEarthquakeMagnitude: (magnitude) => set({ earthquakeMagnitude: magnitude }),

  earthquakeDepth: 10,
  setEarthquakeDepth: (depth) => set({ earthquakeDepth: depth }),

  simulationResults: null,
  setSimulationResults: (results) => set({ simulationResults: results }),

  isSimulationRunning: false,
  setIsSimulationRunning: (val) => set({ isSimulationRunning: val }),
  pendingSimulationRequestId: null,
  setPendingSimulationRequestId: (requestId) => set({ pendingSimulationRequestId: requestId }),

  evacuationOrigin: null,
  evacuationTarget: null,
  evacuationPlan: null,
  evacuationError: '',
  isEvacuationLoading: false,
  isEvacuationModeEnabled: false,
  autoEvacuationPlans: [],
  autoEvacuationError: '',
  isAutoEvacuationLoading: false,
  isPlacingEvacuationOrigin: false,
  isSelectingEvacuationTarget: false,
  setEvacuationOrigin: (origin) => set({ evacuationOrigin: origin }),
  setEvacuationTarget: (target) => set({ evacuationTarget: target }),
  setEvacuationPlan: (plan) => set({ evacuationPlan: plan }),
  setEvacuationError: (error) => set({ evacuationError: error }),
  setIsEvacuationLoading: (isLoading) => set({ isEvacuationLoading: isLoading }),
  setIsEvacuationModeEnabled: (enabled) => set({ isEvacuationModeEnabled: enabled }),
  setAutoEvacuationPlans: (plans) => set({ autoEvacuationPlans: plans }),
  setAutoEvacuationError: (error) => set({ autoEvacuationError: error }),
  setIsAutoEvacuationLoading: (isLoading) => set({ isAutoEvacuationLoading: isLoading }),
  setIsPlacingEvacuationOrigin: (isPlacing) => set({ isPlacingEvacuationOrigin: isPlacing }),
  setIsSelectingEvacuationTarget: (isSelecting) => set({ isSelectingEvacuationTarget: isSelecting }),
  clearEvacuationState: () => set({
    evacuationOrigin: null,
    evacuationTarget: null,
    evacuationPlan: null,
    evacuationError: '',
    isEvacuationLoading: false,
    isEvacuationModeEnabled: false,
    autoEvacuationPlans: [],
    autoEvacuationError: '',
    isAutoEvacuationLoading: false,
    isPlacingEvacuationOrigin: false,
    isSelectingEvacuationTarget: false,
  }),

  clearSimulationState: () => set({
    earthquakeEpicenter: null,
    simulationResults: null,
    isSimulationRunning: false,
    pendingSimulationRequestId: null,
    pendingSimulationInfoPanel: null,
    evacuationOrigin: null,
    evacuationTarget: null,
    evacuationPlan: null,
    evacuationError: '',
    isEvacuationLoading: false,
    isEvacuationModeEnabled: false,
    autoEvacuationPlans: [],
    autoEvacuationError: '',
    isAutoEvacuationLoading: false,
    isPlacingEvacuationOrigin: false,
    isSelectingEvacuationTarget: false,
  }),
});

export const createSimulationSlice = createEarthquakeSlice;

export default createEarthquakeSlice;
